### ISSUE TITLE
Store cache about domain's color

### ISSUE THREAD

**Issue by jacksongoode** [easonwong-de/Adaptive-Tab-Bar-Color#14]
Perhaps storing a very small cache {"domain.com": "r,g,b"} about the prior calculations of each domain might be a way to apply the theme even prior to page loading & calculation?

I think this might also resolve the issue where there is a delay in color application when switching between tab's? I guess ideally there should only be a delay when visiting a domain that hasn't been visited by the user previously.

**Comment by YS-Wong** [comment]
@jacksongoode Great idea. Will add such feature in the future.

**Comment by easonwong-de** [comment]
As tests have shown, the cache mechanism could cause colour flashes. This feature might no longer be considered.

**Comment by jacksongoode** [comment]
> the cache mechanism could cause colour flashes

How would they cause flashes? I imagine it would take the same method as learning the page's color anew but without having to run any scripts.

**Comment by easonwong-de** [comment]
I assume the cache mechanism works like this:

```
web page opened
→ if the page’s colour is not in the cache → get the colour, apply and cache it
→ if it’s in the cache → apply the colour from the cache
```

Problem is, if the actual colour is different from the cached one, the add-on should apply the actual colour. This process will be very obvious, especially for those websites with light and dark themes. If the light-themed colour is cached and the website is opened in dark theme, re-applying the actual colour will make the nav bar flash like flash-bang.

Besides, reading the cache won’t be faster than retrieving the web page colour by a lot.
