### ISSUE TITLE
Not working!!

### ISSUE THREAD

**Issue by sourabh-kumar-jha** [easonwong-de/Adaptive-Tab-Bar-Color#46]
Not working in my system, url becomes invisible and rest everything remains the same even after refreshing the site.

**Comment by YS-Wong** [comment]
@sourabh-kumar-jha I’m terribly sorry for your inconvenience! But I still want to know if the add-on stopped working all of a sudden, or it didn’t work upon installation?

**Comment by easonwong-de** [comment]
With the latest version, this issue could have been adressed.
