### ISSUE TITLE
Active tab color in light mode should not be darker

### ISSUE THREAD

**Issue by mizlan** [easonwong-de/Adaptive-Tab-Bar-Color#51]
I would prefer if the active tab in light mode was either

- lighter than the toolbar (as it is in dark mode)
- or, even better, color-matched with the toolbar

Right now, it is darker:
<img width="261" alt="Screen Shot 2023-04-18 at 10 12 38 AM" src="https://user-images.githubusercontent.com/44309097/232853608-5ddd7436-a35e-4257-ac0a-9fe1609d270b.png">

I don't think there is such an option in the settings right now.

**Comment by mizlan** [comment]
Thank you! I was also considering forking and poking at it... since I don't think it should be too convoluted to arrive at the features I want. :)

**Comment by easonwong-de** [comment]
Forking is always welcomed! Actually, some existing configuration options were added via fork: #23 

I’m working on an overhaul of the option page. Stay tuned :D

**Comment by easonwong-de** [comment]
Here’s a sneak peek of the next version. These options will be presented in a much better way.

<img width="80%" alt="Screenshot 2023-04-21 at 10 55 25" src="https://user-images.githubusercontent.com/16183548/233592637-7e0f52fd-0ae1-40a2-8782-9452f46b8329.png">

**Comment by mizlan** [comment]
Thanks! This is really awesome, I'm loading a local extension to use HEAD right now for the new tab_selected option!

**Comment by easonwong-de** [comment]
Hi, @mizlan, the newly added options are included in the latest patch v1.7.6 now. Further options will be added in the future.

**Comment by mizlan** [comment]
Thanks! Super happy to see this added
